Unindo dados

In [5]:
import pandas as pd

In [6]:
path = r'C:\Users\logistica.wms\OneDrive - SANTA FÉ\Documents\Cursos\Alura\Alura\Pandas - selecionando e agrupando dados\dados\POP2022_Municipios(Municípios).csv'

dados_populacao = pd.read_csv(path,
                              sep=';',
                              encoding='ISO-8859-1',
                              header=1,
                              skipfooter=34,
                              engine='python')

In [7]:
dados_populacao.head(5)

   UF  COD. UF  COD. MUNIC      NOME DO MUNICÍPIO  POPULAÇÃO
0  RO       11          15  Alta Floresta D'Oeste     21.558
1  RO       11          23              Ariquemes    100.896
2  RO       11          31                 Cabixi      5.107
3  RO       11          49                 Cacoal     92.202
4  RO       11          56             Cerejeiras     15.237

In [8]:
df = pd.DataFrame(dados_populacao)

In [9]:
df[df[' POPULAÇÃO '].str.contains('\\(')]

      UF  COD. UF  COD. MUNIC          NOME DO MUNICÍPIO   POPULAÇÃO
16    RO       11         205                Porto Velho   461.748(1)
74    AM       13          29                   Alvarães    15.916(2)
81    AM       13         409                   Barcelos    18.399(3)
83    AM       13         607          Benjamin Constant    37.436(4)
87    AM       13         805                      Borba    33.209(5)
88    AM       13         839                 Caapiranga    13.851(6)
97    AM       13        1605                  Fonte Boa    27.692(7)
98    AM       13        1654                    Guajará    13.809(8)
99    AM       13        1704                    Humaitá    59.504(9)
103   AM       13        1951                  Itamarati   10.783(10)
104   AM       13        2009                 Itapiranga   10.183(11)
105   AM       13        2108                     Japurá    9.281(12)
107   AM       13        2306                      Jutaí   25.048(13)
108   AM       13        2405                     Lábrea   47.003(14)
109   AM       13        2504                 Manacapuru  102.736(15)
117   AM       13        3205                 Novo Airão   15.819(16)
119   AM       13        3403                  Parintins   96.251(17)
120   AM       13        3502                     Pauini   20.351(18)
123   AM       13        3601  Santa Isabel do Rio Negro   14.305(19)
129   AM       13        4062                  Tabatinga   66.837(20)
134   AM       13        4302                    Urucará   18.582(21)
135   AM       13        4401                Urucurituba   24.017(22)
210   PA       15        3754               Jacareacanga   24.742(23)
579   MA       21        7506             Paço do Lumiar  145.752(24)
1526  PE       26        5509                  Ferreiros   15.040(25)
1937  BA       29        9208            Coronel João Sá   17.000(26)
1973  BA       29       12004                  Ibiassucê   10.426(27)
2159  BA       29       27101                    Rodelas   10.303(28)
4215  PR       41       21901         Ribeirão do Pinhal   13.053(29)
5509  GO       52       17609                 Planaltina  108.846(30)

In [10]:
dados_populacao.groupby('UF').sum(numeric_only=True).sort_index(ascending=False)

    COD. UF  COD. MUNIC
UF
TO     2363     1605293
SP    22575    18510133
SE     2100      294557
SC    12390     2894993
RS    21371     5903048
RR      210        4693
RO      572       35443
RN     4008     1276977
RJ     3036      287819
PR    16359     5760146
PI     4928     1275355
PE     4810     1524668
PB     5575     1941029
PA     2160      643582
MT     7191      739592
MS     3950      355226
MG    26443    31545374
MA     4557     1404205
GO    12792     2788737
ES     2496      226710
DF       53         108
CE     4232     1295156
BA    12093     7151757
AP      256        5908
AM      806      134451
AL     2754      487914
AC      264        7719

In [11]:
dados_populacao[dados_populacao[' POPULAÇÃO '].str.contains('\\(')]

      UF  COD. UF  COD. MUNIC          NOME DO MUNICÍPIO   POPULAÇÃO
16    RO       11         205                Porto Velho   461.748(1)
74    AM       13          29                   Alvarães    15.916(2)
81    AM       13         409                   Barcelos    18.399(3)
83    AM       13         607          Benjamin Constant    37.436(4)
87    AM       13         805                      Borba    33.209(5)
88    AM       13         839                 Caapiranga    13.851(6)
97    AM       13        1605                  Fonte Boa    27.692(7)
98    AM       13        1654                    Guajará    13.809(8)
99    AM       13        1704                    Humaitá    59.504(9)
103   AM       13        1951                  Itamarati   10.783(10)
104   AM       13        2009                 Itapiranga   10.183(11)
105   AM       13        2108                     Japurá    9.281(12)
107   AM       13        2306                      Jutaí   25.048(13)
108   AM       13        2405                     Lábrea   47.003(14)
109   AM       13        2504                 Manacapuru  102.736(15)
117   AM       13        3205                 Novo Airão   15.819(16)
119   AM       13        3403                  Parintins   96.251(17)
120   AM       13        3502                     Pauini   20.351(18)
123   AM       13        3601  Santa Isabel do Rio Negro   14.305(19)
129   AM       13        4062                  Tabatinga   66.837(20)
134   AM       13        4302                    Urucará   18.582(21)
135   AM       13        4401                Urucurituba   24.017(22)
210   PA       15        3754               Jacareacanga   24.742(23)
579   MA       21        7506             Paço do Lumiar  145.752(24)
1526  PE       26        5509                  Ferreiros   15.040(25)
1937  BA       29        9208            Coronel João Sá   17.000(26)
1973  BA       29       12004                  Ibiassucê   10.426(27)
2159  BA       29       27101                    Rodelas   10.303(28)
4215  PR       41       21901         Ribeirão do Pinhal   13.053(29)
5509  GO       52       17609                 Planaltina  108.846(30)

In [12]:
dados_populacao = dados_populacao.assign(populacao_sem_parenteses = dados_populacao[' POPULAÇÃO '].replace('\\(\\d{1,2}\\)', '', regex= True),
                                         populacao = lambda x : x.loc[:, 'populacao_sem_parenteses'].replace('\\.', '', regex= True))

In [13]:
dados_populacao = dados_populacao.astype({'populacao' : 'int'})

In [14]:
dados_populacao = dados_populacao.groupby('UF')[['populacao']].sum(numeric_only=True).reset_index()
dados_populacao

    UF  populacao
0   AC     829780
1   AL    3125254
2   AM    3952262
3   AP     774268
4   BA   14659023
5   CE    8936431
6   DF    2923369
7   ES    3975100
8   GO    6950976
9   MA    6800605
10  MG   20732660
11  MS    2833742
12  MT    3784239
13  PA    8442962
14  PB    4030961
15  PE    9051113
16  PI    3270174
17  PR   11835379
18  RJ   16615526
19  RN    3303953
20  RO    1616379
21  RR     634805
22  RS   11088065
23  SC    7762154
24  SE    2211868
25  SP   46024937
26  TO    1584306

In [ ]:
path = r'C:\Users\logistica.wms\OneDrive - SANTA FÉ\Documents\Cursos\Alura\Alura\Pandas - selecionando e agrupando dados\dados\1-SEEG10_GERAL-BR_UF_2022.10.27-FINAL-SITE.xlsx'
dados_emissao = pd.read_excel(path, sheet_name='GEE Estados')

c:\Users\logistica.wms\AppData\Local\Programs\Python\Python314\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [21]:
colunas_info = list(dados_emissao.loc[:, 'Nível 1 - Setor':'Produto'].columns)
colunas_valores = list(dados_emissao.loc[:, 1970:2021].columns)

dados_emissao = dados_emissao.melt( id_vars=        colunas_info, 
                                    value_vars=     colunas_valores, 
                                    var_name=       'Ano', 
                                    value_name=     'Emissão'   )

In [25]:
emissoes_totais = dados_emissao.groupby(['Estado'])[['Ano']].sum().reset_index()

In [27]:
dados_agrupados = pd.merge(emissoes_totais, dados_populacao, left_on="Estado", right_on="UF")

In [28]:
dados_agrupados

   Estado        Ano  UF  populacao
0      AC  234926224  AC     829780
1      AL  353738294  AL    3125254
2      AM  342531566  AM    3952262
3      AP  259103702  AP     774268
4      BA  510009890  BA   14659023
5      CE  367642938  CE    8936431
6      DF  290129736  DF    2923369
7      ES  381651348  ES    3975100
8      GO  354464656  GO    6950976
9      MA  373350068  MA    6800605
10     MG  507727038  MG   20732660
11     MS  428138516  MS    2833742
12     MT  404894932  MT    3784239
13     PA  362039574  PA    8442962
14     PB  381443816  PB    4030961
15     PE  402197016  PE    9051113
16     PI  335060414  PI    3270174
17     PR  455636506  PR   11835379
18     RJ  408215444  RJ   16615526
19     RN  388707436  RN    3303953
20     RO  308807616  RO    1616379
21     RR  245614122  RR     634805
22     RS  439967840  RS   11088065
23     SC  371586046  SC    7762154
24     SE  379991092  SE    2211868
25     SP  479606452  SP   46024937
26     TO  330079646  TO    1584306