Unindo dados

In [ ]:
import pandas as pd

In [2]:
path = r'C:\Users\logistica.wms\OneDrive - SANTA FÉ\Documents\Projetos\alura\gcp\pandasManipulação\dados\POP2022_Municipios(Municípios).csv'
dados_populacao = pd.read_csv(path,
                              sep=';',
                              encoding='ISO-8859-1',
                              header=1,
                              skipfooter=34,
                              engine='python')

In [3]:
dados_populacao

      UF  COD. UF  COD. MUNIC      NOME DO MUNICÍPIO   POPULAÇÃO
0     RO       11          15  Alta Floresta D'Oeste      21.558
1     RO       11          23              Ariquemes     100.896
2     RO       11          31                 Cabixi       5.107
3     RO       11          49                 Cacoal      92.202
4     RO       11          56             Cerejeiras      15.237
...   ..      ...         ...                    ...          ...
5565  GO       52       22005             Vianópolis      14.046
5566  GO       52       22054         Vicentinópolis       8.776
5567  GO       52       22203               Vila Boa       3.686
5568  GO       52       22302          Vila Propício       5.646
5569  DF       53         108               Brasília   2.923.369

[5570 rows x 5 columns]

In [4]:
df = pd.DataFrame(dados_populacao)

In [5]:
df[df[' POPULAÇÃO '].str.contains('\\(')]

      UF  COD. UF  COD. MUNIC          NOME DO MUNICÍPIO   POPULAÇÃO
16    RO       11         205                Porto Velho   461.748(1)
74    AM       13          29                   Alvarães    15.916(2)
81    AM       13         409                   Barcelos    18.399(3)
83    AM       13         607          Benjamin Constant    37.436(4)
87    AM       13         805                      Borba    33.209(5)
88    AM       13         839                 Caapiranga    13.851(6)
97    AM       13        1605                  Fonte Boa    27.692(7)
98    AM       13        1654                    Guajará    13.809(8)
99    AM       13        1704                    Humaitá    59.504(9)
103   AM       13        1951                  Itamarati   10.783(10)
104   AM       13        2009                 Itapiranga   10.183(11)
105   AM       13        2108                     Japurá    9.281(12)
107   AM       13        2306                      Jutaí   25.048(13)
108   AM       13        2405                     Lábrea   47.003(14)
109   AM       13        2504                 Manacapuru  102.736(15)
117   AM       13        3205                 Novo Airão   15.819(16)
119   AM       13        3403                  Parintins   96.251(17)
120   AM       13        3502                     Pauini   20.351(18)
123   AM       13        3601  Santa Isabel do Rio Negro   14.305(19)
129   AM       13        4062                  Tabatinga   66.837(20)
134   AM       13        4302                    Urucará   18.582(21)
135   AM       13        4401                Urucurituba   24.017(22)
210   PA       15        3754               Jacareacanga   24.742(23)
579   MA       21        7506             Paço do Lumiar  145.752(24)
1526  PE       26        5509                  Ferreiros   15.040(25)
1937  BA       29        9208            Coronel João Sá   17.000(26)
1973  BA       29       12004                  Ibiassucê   10.426(27)
2159  BA       29       27101                    Rodelas   10.303(28)
4215  PR       41       21901         Ribeirão do Pinhal   13.053(29)
5509  GO       52       17609                 Planaltina  108.846(30)

In [6]:
dados_populacao.groupby('UF').sum(numeric_only=True).sort_index(ascending=False)

    COD. UF  COD. MUNIC
UF
TO     2363     1605293
SP    22575    18510133
SE     2100      294557
SC    12390     2894993
RS    21371     5903048
RR      210        4693
RO      572       35443
RN     4008     1276977
RJ     3036      287819
PR    16359     5760146
PI     4928     1275355
PE     4810     1524668
PB     5575     1941029
PA     2160      643582
MT     7191      739592
MS     3950      355226
MG    26443    31545374
MA     4557     1404205
GO    12792     2788737
ES     2496      226710
DF       53         108
CE     4232     1295156
BA    12093     7151757
AP      256        5908
AM      806      134451
AL     2754      487914
AC      264        7719

In [3]:
dados_populacao[dados_populacao[' POPULAÇÃO '].str.contains('\\(')]

      UF  COD. UF  COD. MUNIC          NOME DO MUNICÍPIO   POPULAÇÃO
16    RO       11         205                Porto Velho   461.748(1)
74    AM       13          29                   Alvarães    15.916(2)
81    AM       13         409                   Barcelos    18.399(3)
83    AM       13         607          Benjamin Constant    37.436(4)
87    AM       13         805                      Borba    33.209(5)
88    AM       13         839                 Caapiranga    13.851(6)
97    AM       13        1605                  Fonte Boa    27.692(7)
98    AM       13        1654                    Guajará    13.809(8)
99    AM       13        1704                    Humaitá    59.504(9)
103   AM       13        1951                  Itamarati   10.783(10)
104   AM       13        2009                 Itapiranga   10.183(11)
105   AM       13        2108                     Japurá    9.281(12)
107   AM       13        2306                      Jutaí   25.048(13)
108   AM       13        2405                     Lábrea   47.003(14)
109   AM       13        2504                 Manacapuru  102.736(15)
117   AM       13        3205                 Novo Airão   15.819(16)
119   AM       13        3403                  Parintins   96.251(17)
120   AM       13        3502                     Pauini   20.351(18)
123   AM       13        3601  Santa Isabel do Rio Negro   14.305(19)
129   AM       13        4062                  Tabatinga   66.837(20)
134   AM       13        4302                    Urucará   18.582(21)
135   AM       13        4401                Urucurituba   24.017(22)
210   PA       15        3754               Jacareacanga   24.742(23)
579   MA       21        7506             Paço do Lumiar  145.752(24)
1526  PE       26        5509                  Ferreiros   15.040(25)
1937  BA       29        9208            Coronel João Sá   17.000(26)
1973  BA       29       12004                  Ibiassucê   10.426(27)
2159  BA       29       27101                    Rodelas   10.303(28)
4215  PR       41       21901         Ribeirão do Pinhal   13.053(29)
5509  GO       52       17609                 Planaltina  108.846(30)

In [9]:
dados_populacao = dados_populacao.assign(populacao_sem_parenteses = dados_populacao[' POPULAÇÃO '].replace('\\(\\d{1,2}\\)', '', regex= True),
                                         populacao = lambda x : x.loc[:, 'populacao_sem_parenteses'].replace('\\.', '', regex= True))

In [17]:
dados_populacao = dados_populacao.astype({'populacao' : 'int'})

In [ ]:
dados_populacao.groupby('UF')[['populacao']].mean(numeric_only=True)

    populacao
UF
AC     829780
AL    3125254
AM    3952262
AP     774268
BA   14659023
CE    8936431
DF    2923369
ES    3975100
GO    6950976
MA    6800605
MG   20732660
MS    2833742
MT    3784239
PA    8442962
PB    4030961
PE    9051113
PI    3270174
PR   11835379
RJ   16615526
RN    3303953
RO    1616379
RR     634805
RS   11088065
SC    7762154
SE    2211868
SP   46024937
TO    1584306